### ISSUE TITLE
Collect Raw Data

### ISSUE THREAD

**Issue by amillert** [amillert/pic2story#7]
Data mainly in the form of stories. Let's share some links in the comments.

**Comment by Namibillow** [comment]
Kids stories --------
https://www.freechildrenstories.com/
https://monkeypen.com/pages/free-childrens-books
https://research.fb.com/downloads/babi/     Click "Children's Book Test" for downloading the dataset 

Short stories -------
https://www.gutenberg.org/ebooks/search/?query=short+stories

**Comment by amillert** [comment]
https://www.gutenberg.org/policy/robot_access.html
